### ISSUE TITLE
Shortcut doesnt work

### ISSUE THREAD

**Issue by CodeMeGel** [Irvel/screenshot-to-yoink#3]
Hi, I found this simple Script on reddit. I tried it on alfred but the shortcut option shift 3 and 4 doesnt work. The only time it is working is by using alfred spotlight and type Yoink and it show send directly to yoink

**Comment by Irvel** [comment]
Hi! Sorry I created this years ago but I no longer use it given that I stopped owning a Mac also years ago. 

I'll archive the repo.
